### Crear categoría
POST http://localhost:3000/api/category
Content-Type: application/json

{
  "name": "Verduras",
  "description": "Verduras frescas"
}

### Listar productos
GET http://localhost:3000/api/products


